# 系统配置
system:
  # 开发者
  author: tangzedong.programmer@gmail.com
  # 是否使用spring cache注解
  spring-cache: false
  # 是否使用swagger2注解
  swagger: false
  # 生成指定模块
  # 不指定的时候为生成所有
  # 可选择值：Domain/Mapper/Service/Factory/Controller/XML
  modules:
# 基类配置
basic:
  # domain基类【需包含包完整路径】
  # 无默认值
  basic-domain:
  # mapper基类【需包含包完整路径】
  # 默认为mybatis-plus的mapper基类
  # 默认值：com.baomidou.mybatisplus.core.mapper.BaseMapper;
  basic-mapper:
  # service基类【需包含包完整路径】
  # 默认为mybatis-plus的service基类
  # 默认值：com.baomidou.mybatisplus.extension.service.impl.ServiceImpl
  basic-service:

# 数据库相关配置
database:
  # 表前缀过滤，支持多过滤条件
  table-prefix:
    -
  # 列前缀过滤，支持多过滤条件
  column-prefix:
    -
  # 【！必须参数】生成表名称，支持多表同时生成
  generator-table-name:
    -
  # 使用基类忽略的属性，支持多过滤条件
  ignore-attributes:
  # 版本的字段，匹配字段会使用Mybaits-plus的@Version注解
  version:
  # 版本的字段，匹配字段会使用Mybaits-plus的@TableLogic注解
  del-flag:
  # 方言，仅支持Mysql、Oracle、SqlServer、PostgreSql
  # 默认值：Mysql
  dialect: Mysql

#路径配置
path:
  # 项目路径，默认为项目的根目录
  root-path: /
  # 【！建议参数】包路径
  package-path:
  # 【！建议参数】模块名称
  module-name:
  # 控制层路径，默认情况 rootPath / packagePath / moduleName / controller
  # 当控制层有值（用户指定路径），控制层路径为 rootPath / controllerPath
  controller-path:
  # 服务层路径，默认情况下是 rootPath / packagePath / moduleName / service
  # 当服务层有值（用户指定路径），服务层路径为 rootPath / servicePath
  service-path:
  # 持久层路径，默认情况下是 rootPath / packagePath / moduleName / mapper
  # 当持久层有值（用户指定路径），持久层路径为 rootPath / mapperPath
  mapper-path:
  # 实体层路径，默认情况下是 rootPath / packagePath / moduleName / domain
  # 当实体层有值（用户指定路径），实体层路径为 rootPath / mapperPath
  domain-path:
  # 服务工厂类路径，默认情况下是 rootPath / packagePath / moduleName / factory
  # 当服务工厂类有值（用户指定路径），实体层路径为 rootPath / factoryPath
  factory-path:
  # mybatis配置文件路径，默认情况下是 rootPath / src / main / resources / mapper /moduleName
  # 当mybatis配置文件有值（用户指定路径），实体层路径为 rootPath / src / main / resources / xmlPath
  xml-path:

# 数据库的配置
mybatis:
  # 【！必须参数】数据库密码
  password:
  # 【！必须参数】数据库链接地址
  url:
  # 【！必须参数】数据库用户名
  username:
