# 基础配置
properties:
  config:
    # 模块包路径
    packagePath: com.dawn.oneforall
    # 模块名称
    moduleName: spark
    # 作者
    author: tangzedong.programmer@gmail.com
    # 需要过滤的表前缀，多行以逗号分隔开
    tablePrefix: spark_
    # 需要过滤的列前缀，多行以逗号分隔开
    columnPrefix:
    # 文件输出路径
    fileOutputPath: /Users/tangzedong/temp
    # 乐观锁字段，字段会加入mybatis-plus的@Version注解
    versionFiled:
    # 使用基类忽略的属性，定以后不生成java bean成员属性
    ignoreAttributes:
      - id
      - creation_time
      - modification_time
      - delete_flag
      - note
    # 需要生成代码的数据库表名称，数组
    generatorTableName:
      - spark_price
      - spark_album
      - spark_basic_info
      - spark_browse
      - spark_contact
      - spark_contact_mark
      - spark_details_info
      - spark_experience
    # 数据库 可选值 Mysql，Oracle，默认为Mysql
    sqlType: Mysql
    # 常用框架配置使用
    usualFrameConfig:
      # 是否使用swagger注解，默认为true，会在Domain以及Controller层加上swagger相关注解
      useSwagger: true
      # 是否使用shiro安全校验注解，默认为false，会在controller层上加上shiro相关注解
      useShiro: false
    # 服务层基类配置
    baseServiceConfig:
      # 服务层的基类包相对路径{eg:com.generator.common.base.BasicService}
      packageRelativePath:
    # 实体类基类配置
    baseEntityConfig:
      # 实体类的基类类包相对路径{eg:com.generator.common.base.BasicEntity}
      packageRelativePath: com.dawn.oneforall.common.base.domain.DataEntity
    # controller层返回视图对象配置信息
    ctrlResultConfig:
      # controller层返回对象视图相对路径{eg:com.generator.common.base.JsonResult}
      packageRelativePath:
